name: Build MelonLoader

on:
  push:
    branches: [ ML-LLC ]
  pull_request:
    branches: [ ML-LLC ]
  workflow_dispatch:

jobs:
  build_core_release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: Build Melonloader Core
        shell: cmd
        run: msbuild /restore /p:Configuration=Release /p:Platform="Windows - x64"
      - name: Upload core artifact
        uses: actions/upload-artifact@v3
        with:
          name: MLCoreRelease
          path: Output/Release/MelonLoader/
  build_rust_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          # Target triple to install for this toolchain
          targets: i686-pc-windows-msvc, x86_64-pc-windows-msvc
        # Build Rust Release
      - name: Build Rust Release | Windows - x86
        shell: cmd
        run: cargo +nightly build --target i686-pc-windows-msvc --release
      - name: Build Rust Release | Windows - x64
        shell: cmd
        run: cargo +nightly build --target x86_64-pc-windows-msvc --release
        # Build Rust Debug
      - name: Build Rust Debug | Windows - x86
        shell: cmd
        run: cargo +nightly build --target i686-pc-windows-msvc
      - name: Build Rust Debug | Windows - x64
        shell: cmd
        run: cargo +nightly build --target x86_64-pc-windows-msvc
        # Upload Proxy Release - x86
      - name: Upload Proxy Release | Windows x86
        uses: actions/upload-artifact@v3
        with:
          name: MLProxyX86-Windows-Release
          path: target/i686-pc-windows-msvc/release/version.dll
        # Upload Bootstrap Release - x86
      - name: Upload Bootstrap Release | Windows x86
        uses: actions/upload-artifact@v3
        with:
          name: MLBootstrapX86-Windows-Release
          path: target/i686-pc-windows-msvc/release/Bootstrap.dll
        # Upload Proxy Release - x64
      - name: Upload Proxy Release | Windows x64
        uses: actions/upload-artifact@v3
        with:
          name: MLProxyX64-Windows-Release
          path: target/x86_64-pc-windows-msvc/release/version.dll
        # Upload Bootstrap Release - x64
      - name: Upload Bootstrap Release | Windows x64
        uses: actions/upload-artifact@v3
        with:
          name: MLBootstrapX64-Windows-Release
          path: target/x86_64-pc-windows-msvc/release/Bootstrap.dll
        # Upload Proxy Debug - x86
      - name: Upload Proxy Debug | Windows x86
        uses: actions/upload-artifact@v3
        with:
          name: MLProxyX86-Windows-Debug
          path: target/i686-pc-windows-msvc/debug/version.dll
        # Upload Bootstrap Debug - x86
      - name: Upload Bootstrap Debug | Windows x86
        uses: actions/upload-artifact@v3
        with:
          name: MLBootstrapX86-Windows-Debug
          path: target/i686-pc-windows-msvc/debug/Bootstrap.dll
        # Upload Proxy Debug - x64
      - name: Upload Proxy Debug | Windows x64
        uses: actions/upload-artifact@v3
        with:
          name: MLProxyX64-Windows-Debug
          path: target/x86_64-pc-windows-msvc/debug/version.dll
        # Upload Bootstrap Debug - x64
      - name: Upload Bootstrap Debug | Windows x64
        uses: actions/upload-artifact@v3
        with:
          name: MLBootstrapX64-Windows-Debug
          path: target/x86_64-pc-windows-msvc/debug/Bootstrap.dll
  finalize_x64_release_zip_windows:
    runs-on: windows-latest
    needs: [build_core_release, build_rust_windows]
    steps:
      - uses: actions/checkout@v3
      - name: Download core artifact
        uses: actions/download-artifact@v3
        with:
          name: MLCoreRelease
          path: Output/Release/x64/MelonLoader/
      - name: Download proxy x64
        uses: actions/download-artifact@v3
        with:
          name: MLProxyX64-Windows-Release
          path: Output/Release/x64/
      - name: Download bootstrap x64
        uses: actions/download-artifact@v3
        with:
          name: MLBootstrapX64-Windows-Release
          path: Output/Release/x64/MelonLoader/Dependencies/
      - name: Package x64 zip
        shell: cmd
        run: |
          echo Copying Managed Libs...
          mkdir Output\Release\x64\MelonLoader\Managed\
          xcopy BaseLibs\Managed Output\Release\x64\MelonLoader\Managed\ /E /H /Y
          echo.
          echo Copying Dobby x64...
          xcopy BaseLibs\dobby_x64.dll Output\Release\x64\dobby.dll*
          echo. 
          echo Copying documentation files...
          mkdir Output\Release\x64\MelonLoader\Documentation
          copy CHANGELOG.md Output\Release\x64\MelonLoader\Documentation\
          copy LICENSE.md Output\Release\x64\MelonLoader\Documentation\
          copy NOTICE.txt Output\Release\x64\MelonLoader\Documentation\
          copy README.md Output\Release\x64\MelonLoader\Documentation\
      - uses: actions/upload-artifact@v3
        name: Upload Zip | Windows - x64
        with:
          name: MelonLoader.Windows.x64.CI.Release
          path: ./Output/Release/x64/*
  cleanup_artifacts:
    runs-on: windows-latest
    needs: [ finalize_x64_release_zip_windows ]
    steps:
      - uses: GeekyEggo/delete-artifact@v2.0.0
        with:
          name: |
            MLCoreDebug
            MLCoreRelease
            MLProxyX64-Windows-Release
            MLBootstrapX64-Windows-Release